package io.github.meeting.copilot.enums.gemini.safety;

/**
 * @author HydroCarbon
 * @since 2024-03-01
 */
public enum HarmCategory {
    //HARM_CATEGORY_SEXUALLY_EXPLICIT
    //HARM_CATEGORY_HATE_SPEECH
    //HARM_CATEGORY_HARASSMENT
    //HARM_CATEGORY_DANGEROUS_CONTENT

    HARM_CATEGORY_SEXUALLY_EXPLICIT,
    HARM_CATEGORY_HATE_SPEECH,
    HARM_CATEGORY_HARASSMENT,
    HARM_CATEGORY_DANGEROUS_CONTENT;
}
